# config_human_30x.yaml
project:
  name: human_30x_trio_demo
  organism: homo_sapiens
  reference:
    name: GRCh38_full_analysis_set_plus_decoy_hla
    fasta_url: "http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/GRCh38_reference_genome/GRCh38_full_analysis_set_plus_decoy_hla.fa"
    fasta_md5: "a2da5bdf... (opcional)"
    # Se já tiver o FASTA localmente, você pode usar:
    # fasta_path: "/dados/GENOMICS_DATA/ref/GRCh38_full_analysis_set_plus_decoy_hla.fa"

storage:
  base_dir: "/dados/GENOMICS_DATA"
  work_dir: "/dados/GENOMICS_DATA/work"
  temp_dir: "/dados/GENOMICS_DATA/tmp"
  keep_intermediates: true   # útil para retomar e inspecionar

download:
  tool: sra_toolkit            # prefetch + fasterq-dump
  use_ascp: false              # mude para true se tiver Aspera configurado
  threads: 8
  # Se preferir baixar direto os FASTQs via FTP, seu script pode respeitar 'direct_fastq_urls' (opcional)

execution:
  verbose: true
  resume: true                 # não reprocessa o que já existe
  skip_existing: true          # idem para baixados/gerados
  progress_interval_sec: 60    # estimativas periódicas

size_control:
  downsample:
    enabled: true
    fraction: 0.25             # 25% (~7.5×); aumente para 1.0 quando quiser o 30× completo
  # Ou, alternativamente, limite de disco:
  # disk_budget_gb: 650        # o pipeline pode pausar/adiar amostras para não estourar

# Amostras 30× (NYGC 1000G GRCh38); cada 'runs' aceita SRR/ERR/DRR
samples:
  - sample_id: NA12878        # filha (HG001 / GM12878)
    study: PRJEB31736         # 1000G 30× (lote principal)
    runs:
      - ERR3239334            # FASTQs gerados pelo ENA: ERR3239334_1.fastq.gz / _2.fastq.gz
    notes: "CRAM 'final' disponível: ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR323/ERR3239334/NA12878.final.cram"

  - sample_id: NA12891        # pai
    study: PRJEB36890         # 1000G 30× (trios adicionais)
    runs:
      - ERR3989341            # ENA fornece FASTQ gerado para este run
    notes: "CRAM 'final': ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR398/ERR3989341/NA12891.final.cram"

  - sample_id: NA12892        # mãe
    study: PRJEB36890
    runs:
      - ERR3989342            # ENA fornece FASTQ gerado para este run
    notes: "CRAM 'final': ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR398/ERR3989342/NA12892.final.cram"

# Etapas do pipeline (ajuste conforme seu script)
steps:
  - fetch_fastqs          # prefetch/fasterq-dump; respeita skip_existing/resume
  - qc_reads              # FastQC/MultiQC (se configurados)
  - align_and_sort        # BWA-MEM/BWA-MEM2 + samtools
  - mark_duplicates       # GATK MarkDuplicatesSpark/picard
  - bqsr                  # GATK BaseRecalibrator/applyBQSR (opcional)
  - call_genes            # sua extração/varredura de genes (exons/introns) e comparação
  - summarize             # relatórios e métricas

# Parâmetros de alinhamento/chamada (exemplo; alinhe com o que seu script usa)
params:
  bwa_mem2_threads: 16
  gatk_threads: 8
  target_gene_list: null   # ou caminho para um painel BED/genes de interesse

