general:
  base_dir: "/dados/GENOMICS_DATA"
  assembly_name: "GRCh38"
  ref_fa_url: "https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_46/GRCh38.primary_assembly.genome.fa.gz"
  gtf_url:     "https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_46/gencode.v46.primary_assembly.annotation.gtf.gz"

  threads: 16
  mem_gb: 64
  default_read_type: "short"
  adapters: { fwd: "AGATCGGAAGAGC", rev: "AGATCGGAAGAGC" }

  use_cram: true
  cleanup:
    remove_sorted_bam: true
    remove_bam_after_cram: true
  downsample_frac: 0.0      # já é 30×; não precisa reduzir
  downsample_seed: 123

  call_variants: true
  annotate_vars: true
  rnaseq: false

  force_refs: false
  force_indexes: false
  vep_cache_dir: ""
  space_guard_gb_min: 100

dna_samples:
  - id: "NA12878_30x_NYGC"   # ou outro indivíduo 30×
    source: "sra"
    sra_ids: ["SRRxxxxxxx", "SRRyyyyyyy"]  # substitua pelos SRRs 30× da amostra escolhida
    read_type: "short"

