#!/usr/bin/env python3
"""
VCF to 23andMe Converter
=========================

Converts VCF (Variant Call Format) files to 23andMe raw data format (V3 or V5).
Optionally annotates VCF with dbSNP rsIDs via bcftools before conversion.

Usage:
    python vcf_to_23andme.py --config configs/default.yaml

Author: genomics pipeline
License: MIT
"""

import argparse
import csv
import gzip
import io
import os
import re
import subprocess
import sys
import tempfile
import zipfile
from datetime import datetime
from pathlib import Path

import yaml

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

GRCH37_CONTIG_LENGTHS = {
    "1": 249250621, "2": 243199373, "3": 198022430, "4": 191154276,
    "5": 180915260, "6": 171115067, "7": 159138663, "8": 146364022,
    "9": 141213431, "10": 135534747, "11": 135006516, "12": 133851895,
    "13": 115169878, "14": 107349540, "15": 102531392, "16": 90354753,
    "17": 81195210, "18": 78077248, "19": 59128983, "20": 63025520,
    "21": 48129895, "22": 51304566, "X": 155270560, "Y": 59373566,
}

GRCH38_CONTIG_LENGTHS = {
    "1": 248956422, "2": 242193529, "3": 198295559, "4": 190214555,
    "5": 181538259, "6": 170805979, "7": 159345973, "8": 145138636,
    "9": 138394717, "10": 133797422, "11": 135086622, "12": 133275309,
    "13": 114364328, "14": 107043718, "15": 101991189, "16": 90338345,
    "17": 83257441, "18": 80373285, "19": 58617616, "20": 64444167,
    "21": 46709983, "22": 50818468, "X": 156040895, "Y": 57227415,
}

DBSNP_URLS = {
    "GRCh37": {
        "vcf": "https://ftp.ncbi.nih.gov/snp/organisms/human_9606_b151_GRCh37p13/VCF/common_all_20180423.vcf.gz",
        "tbi": "https://ftp.ncbi.nih.gov/snp/organisms/human_9606_b151_GRCh37p13/VCF/common_all_20180423.vcf.gz.tbi",
        "filename": "dbsnp_b151_GRCh37_common.vcf.gz",
    },
    "GRCh38": {
        "vcf": "https://ftp.ncbi.nih.gov/snp/organisms/human_9606/VCF/common_all_20180418.vcf.gz",
        "tbi": "https://ftp.ncbi.nih.gov/snp/organisms/human_9606/VCF/common_all_20180418.vcf.gz.tbi",
        "filename": "dbsnp_b151_GRCh38_common.vcf.gz",
    },
}

# RefSeq accession -> numeric chromosome (GRCh38 dbSNP uses RefSeq names)
REFSEQ_TO_CHROM = {
    "NC_000001.11": "1", "NC_000002.12": "2", "NC_000003.12": "3",
    "NC_000004.12": "4", "NC_000005.10": "5", "NC_000006.12": "6",
    "NC_000007.14": "7", "NC_000008.11": "8", "NC_000009.12": "9",
    "NC_000010.11": "10", "NC_000011.10": "11", "NC_000012.12": "12",
    "NC_000013.11": "13", "NC_000014.9": "14", "NC_000015.10": "15",
    "NC_000016.10": "16", "NC_000017.11": "17", "NC_000018.10": "18",
    "NC_000019.10": "19", "NC_000020.11": "20", "NC_000021.9": "21",
    "NC_000022.11": "22", "NC_000023.11": "X", "NC_000024.10": "Y",
    "NC_012920.1": "MT",
}

ILLUMINA_PANEL_URLS = {
    "V5": {
        "url": "https://webdata.illumina.com/downloads/productfiles/global-screening-array/v1-0/infinium-global-screening-array-v1-0-c1-manifest-file-csv-build37.zip",
        "download_name": "illumina_gsa_v1_manifest.zip",
        "is_zip": True,
        "panel_file": "panel_23andme_V5.txt",
        "chip_name": "Infinium Global Screening Array v1.0",
    },
    "V3": {
        "url": "https://webdata.illumina.com/downloads/ProductFiles/HumanOmniExpress/v1-1/HumanOmniExpress-12-v1-1-C.csv",
        "download_name": "illumina_omniexpress_v1.1_manifest.csv",
        "is_zip": False,
        "panel_file": "panel_23andme_V3.txt",
        "chip_name": "HumanOmniExpress-12 v1.1",
    },
}

HEADER_23ANDME_V5 = """\
# This data file generated by 23andMe at: {date}
#
# This file contains raw genotype data, including data that is not used in 23andMe reports.
# This data has undergone a general quality review however only a subset of markers have been
# individually validated for accuracy. As such, this data is suitable only for research,
# educational, and informational use and not for medical or other use.
#
# Below is a text version of your data.  Fields are TAB-separated
# Each line corresponds to a single SNP.  For each SNP, we provide its identifier
# (an rsid or an internal id), its location on the reference human genome, and the
# genotype call oriented with respect to the plus strand on the human reference sequence.
# We are using the reference human assembly {build_label}.
#
# Note that it is possible that data downloaded at different times may be different due to ongoing
# improvements in our ability to call genotypes. More information about these changes can be found at:
# https://you.23andme.com/
#
# More information on reference human assembly builds:
# https://www.ncbi.nlm.nih.gov/assembly/GCF_000001405.13/
#
# rsid\tchromosome\tposition\tgenotype
"""

HEADER_23ANDME_V3 = """\
# This data file generated by 23andMe at: {date}
#
# Below is a text version of your data.  Fields are TAB-separated
# Each line corresponds to a single SNP.  For each SNP, we provide its identifier
# (an rsid or an internal id), its location on the reference human genome, and the
# genotype call oriented with respect to the plus strand on the human reference sequence.
# We are using the reference human assembly {build_label}.
#
# rsid\tchromosome\tposition\tgenotype
"""

# ---------------------------------------------------------------------------
# Utility functions
# ---------------------------------------------------------------------------


def load_config(config_path: Path) -> dict:
    """Load YAML configuration file."""
    with open(config_path, "r", encoding="utf-8") as f:
        config = yaml.safe_load(f)
    return config


def open_file(filename: str):
    """Open a regular or gzipped file automatically."""
    if str(filename).endswith(".gz"):
        return gzip.open(filename, "rt", encoding="utf-8")
    return open(filename, "r", encoding="utf-8")


def normalize_chrom(chrom: str) -> str:
    """Strip 'chr' prefix and normalise MT."""
    c = chrom.removeprefix("chr")
    if c == "M":
        c = "MT"
    return c


def run_cmd(cmd: list[str], description: str = "") -> subprocess.CompletedProcess:
    """Run an external command, raising on failure."""
    desc = description or " ".join(cmd[:3])
    try:
        result = subprocess.run(cmd, check=True, capture_output=True, text=True)
        return result
    except FileNotFoundError:
        print(f"Error: command not found: {cmd[0]}")
        print(f"  Make sure the genomics conda environment is activated.")
        sys.exit(1)
    except subprocess.CalledProcessError as exc:
        print(f"Error running {desc}:")
        print(f"  Command: {' '.join(cmd)}")
        if exc.stderr:
            print(f"  stderr: {exc.stderr.strip()}")
        sys.exit(1)


# ---------------------------------------------------------------------------
# Genome build detection
# ---------------------------------------------------------------------------


def detect_genome_build(vcf_path: str) -> str | None:
    """
    Detect genome build (GRCh37 or GRCh38) from VCF headers.

    Strategy (in priority order):
      1. ##reference= line containing GRCh37/hg19 or GRCh38/hg38
      2. ##contig= lines with known chromosome lengths
      3. Chromosome naming convention (chr prefix suggests GRCh38)

    Returns "GRCh37", "GRCh38", or None.
    """
    grch37_hits = 0
    grch38_hits = 0
    has_chr_prefix = False
    has_no_chr_prefix = False

    with open_file(vcf_path) as f:
        for line in f:
            if not line.startswith("#"):
                break

            if line.startswith("##reference="):
                ref_line = line.lower()
                if "grch37" in ref_line or "hg19" in ref_line or "b37" in ref_line:
                    return "GRCh37"
                if "grch38" in ref_line or "hg38" in ref_line:
                    return "GRCh38"

            if line.startswith("##contig="):
                m = re.search(r"ID=(\S+?)[,>]", line)
                m_len = re.search(r"length=(\d+)", line)
                if m and m_len:
                    contig_id = normalize_chrom(m.group(1))
                    contig_len = int(m_len.group(1))

                    if contig_id in GRCH37_CONTIG_LENGTHS and GRCH37_CONTIG_LENGTHS[contig_id] == contig_len:
                        grch37_hits += 1
                    if contig_id in GRCH38_CONTIG_LENGTHS and GRCH38_CONTIG_LENGTHS[contig_id] == contig_len:
                        grch38_hits += 1

                    raw_id = m.group(1)
                    if raw_id.startswith("chr"):
                        has_chr_prefix = True
                    elif raw_id in ("1", "2", "3", "X", "Y"):
                        has_no_chr_prefix = True

            if line.startswith("#CHROM"):
                break

    if grch37_hits > 0 or grch38_hits > 0:
        if grch37_hits > grch38_hits:
            return "GRCh37"
        if grch38_hits > grch37_hits:
            return "GRCh38"

    if has_chr_prefix and not has_no_chr_prefix:
        return "GRCh38"
    if has_no_chr_prefix and not has_chr_prefix:
        return "GRCh37"

    return None


# ---------------------------------------------------------------------------
# VCF annotation with dbSNP
# ---------------------------------------------------------------------------


def vcf_needs_annotation(vcf_path: str, sample_lines: int = 500) -> bool:
    """
    Check whether a VCF needs rsID annotation by sampling variant lines.
    Returns True if >80% of sampled variants have '.' in the ID column.
    """
    total = 0
    missing = 0
    with open_file(vcf_path) as f:
        for line in f:
            if line.startswith("#"):
                continue
            fields = line.split("\t", 4)
            if len(fields) < 4:
                continue
            total += 1
            if fields[2] == ".":
                missing += 1
            if total >= sample_lines:
                break

    if total == 0:
        return False
    ratio = missing / total
    return ratio > 0.8


def detect_vcf_chrom_style(vcf_path: str) -> str:
    """
    Detect chromosome naming style in a VCF file.
    Returns "chr" (chr1, chr2...), "nochr" (1, 2...), or "refseq" (NC_000001.11...).
    """
    with open_file(vcf_path) as f:
        for line in f:
            if line.startswith("#"):
                if line.startswith("##contig="):
                    m = re.search(r"ID=(\S+?)[,>]", line)
                    if m:
                        cid = m.group(1)
                        if cid.startswith("NC_"):
                            return "refseq"
                        if cid.startswith("chr"):
                            return "chr"
                        if cid in ("1", "2", "3", "X", "Y"):
                            return "nochr"
                continue
            fields = line.split("\t", 2)
            if fields:
                chrom = fields[0]
                if chrom.startswith("NC_"):
                    return "refseq"
                if chrom.startswith("chr"):
                    return "chr"
                return "nochr"
    return "nochr"


def download_file(url: str, dest: Path) -> None:
    """Download a file using wget (with resume support) or curl as fallback."""
    dest.parent.mkdir(parents=True, exist_ok=True)

    if dest.exists():
        print(f"  Already downloaded: {dest.name}")
        return

    partial = dest.with_suffix(dest.suffix + ".partial")
    print(f"  Downloading {dest.name}...")
    print(f"    URL: {url}")

    try:
        subprocess.run(
            ["wget", "-q", "--show-progress", "-c", "-O", str(partial), url],
            check=True,
        )
    except FileNotFoundError:
        subprocess.run(
            ["curl", "-L", "-C", "-", "-o", str(partial), url],
            check=True,
        )

    partial.rename(dest)
    print(f"  Download complete: {dest.name}")


def _build_chrom_map_file(source_style: str, target_style: str, ref_dir: Path) -> Path | None:
    """
    Create a chromosome name mapping file for bcftools annotate --rename-chrs.
    Maps chromosome names in the dbSNP file to match the input VCF style.
    Returns the path to the mapping file, or None if no mapping is needed.
    """
    if source_style == target_style:
        return None

    standard_chroms = [str(i) for i in range(1, 23)] + ["X", "Y", "MT"]

    mapping = {}
    if source_style == "refseq":
        chrom_to_refseq = {v: k for k, v in REFSEQ_TO_CHROM.items()}
        for c in standard_chroms:
            refseq = chrom_to_refseq.get(c)
            if refseq:
                if target_style == "chr":
                    target = f"chr{c}" if c != "MT" else "chrM"
                else:
                    target = c
                mapping[refseq] = target
    elif source_style == "nochr" and target_style == "chr":
        for c in standard_chroms:
            mapping[c] = f"chr{c}" if c != "MT" else "chrM"
    elif source_style == "chr" and target_style == "nochr":
        for c in standard_chroms:
            src = f"chr{c}" if c != "MT" else "chrM"
            mapping[src] = c
    else:
        return None

    if not mapping:
        return None

    map_path = ref_dir / f"chrom_map_{source_style}_to_{target_style}.txt"
    if not map_path.exists():
        with open(map_path, "w") as f:
            for src, dst in mapping.items():
                f.write(f"{src} {dst}\n")
    return map_path


def ensure_dbsnp_available(build: str, ref_dir: Path, vcf_chrom_style: str) -> Path:
    """
    Ensure a dbSNP VCF file with matching chromosome names is available in ref_dir.
    Downloads if necessary and renames chromosomes if styles differ.
    Returns the path to the ready-to-use dbSNP VCF.
    """
    ref_dir = Path(ref_dir)
    ref_dir.mkdir(parents=True, exist_ok=True)

    info = DBSNP_URLS[build]
    raw_vcf = ref_dir / info["filename"]
    raw_tbi = ref_dir / (info["filename"] + ".tbi")

    download_file(info["vcf"], raw_vcf)
    download_file(info["tbi"], raw_tbi)

    dbsnp_style = detect_vcf_chrom_style(str(raw_vcf))
    print(f"  dbSNP chromosome style: {dbsnp_style}, input VCF style: {vcf_chrom_style}")

    if dbsnp_style == vcf_chrom_style:
        return raw_vcf

    renamed_name = raw_vcf.stem.replace(".vcf", "") + f".{vcf_chrom_style}.vcf.gz"
    renamed_vcf = ref_dir / renamed_name

    if renamed_vcf.exists() and Path(str(renamed_vcf) + ".tbi").exists():
        print(f"  Using pre-existing renamed dbSNP: {renamed_vcf.name}")
        return renamed_vcf

    chrom_map = _build_chrom_map_file(dbsnp_style, vcf_chrom_style, ref_dir)
    if chrom_map is None:
        print(f"  Warning: could not build chromosome name mapping, using dbSNP as-is")
        return raw_vcf

    print(f"  Renaming dbSNP chromosomes ({dbsnp_style} -> {vcf_chrom_style})...")
    run_cmd(
        ["bcftools", "annotate", "--rename-chrs", str(chrom_map),
         str(raw_vcf), "-Oz", "-o", str(renamed_vcf)],
        "bcftools annotate --rename-chrs",
    )
    run_cmd(
        ["bcftools", "index", "-t", str(renamed_vcf)],
        "bcftools index",
    )
    print(f"  Renamed dbSNP saved: {renamed_vcf.name}")
    return renamed_vcf


def _ensure_vcf_indexed(vcf_path: str) -> str:
    """
    Ensure a VCF file is bgzipped and tabix-indexed for bcftools.
    The original input file is NEVER modified.

    If the .tbi index already exists, returns the path unchanged.
    Otherwise creates a bgzipped copy with a .bgz.vcf.gz suffix and indexes it.
    Returns the path to the indexed VCF (may differ from input).
    """
    vcf = Path(vcf_path)
    tbi = Path(f"{vcf}.tbi")
    csi = Path(f"{vcf}.csi")

    if tbi.exists() or csi.exists():
        return vcf_path

    if str(vcf).endswith(".vcf.gz"):
        result = subprocess.run(
            ["bcftools", "index", "-t", str(vcf)],
            capture_output=True, text=True,
        )
        if result.returncode == 0:
            return vcf_path

    stem = vcf.name
    for ext in (".vcf.gz", ".vcf"):
        if stem.endswith(ext):
            stem = stem[: -len(ext)]
            break
    bgz_vcf = vcf.parent / f"{stem}.bgz.vcf.gz"

    if bgz_vcf.exists() and Path(f"{bgz_vcf}.tbi").exists():
        print(f"  Using existing bgzipped copy: {bgz_vcf.name}")
        return str(bgz_vcf)

    print(f"  Creating bgzipped copy for indexing (original file is not modified)...")
    run_cmd(
        ["bcftools", "view", str(vcf), "-Oz", "-o", str(bgz_vcf)],
        "bcftools view (bgzip copy)",
    )
    run_cmd(
        ["bcftools", "index", "-t", str(bgz_vcf)],
        "bcftools index",
    )
    print(f"  Indexed copy created: {bgz_vcf.name}")
    return str(bgz_vcf)


def annotate_vcf_with_dbsnp(vcf_path: str, build: str, ref_dir: str) -> str:
    """
    Annotate a VCF file with dbSNP rsIDs if most variants lack them.

    Steps:
      1. Check if annotation is needed (sample variant lines)
      2. Download dbSNP to ref_dir if not already present
      3. Handle chromosome name mismatches
      4. Run bcftools annotate -c ID
      5. Save annotated VCF alongside the original with .rsid.vcf.gz suffix

    Returns the path to the annotated VCF (or the original if annotation was skipped).
    """
    vcf = Path(vcf_path)
    ref = Path(ref_dir)

    stem = vcf.name
    for ext in (".vcf.gz", ".vcf"):
        if stem.endswith(ext):
            stem = stem[: -len(ext)]
            break
    annotated_vcf = vcf.parent / f"{stem}.rsid.vcf.gz"

    if annotated_vcf.exists():
        print(f"  Annotated VCF already exists: {annotated_vcf.name}")
        print(f"  Skipping re-annotation. Delete the file to force re-annotation.")
        return str(annotated_vcf)

    print(f"Checking whether VCF needs rsID annotation...")
    if not vcf_needs_annotation(vcf_path):
        print(f"  VCF already has rsIDs, skipping annotation.")
        return vcf_path

    print(f"  Most variants lack rsIDs. Will annotate with dbSNP.")

    vcf_style = detect_vcf_chrom_style(vcf_path)
    dbsnp_vcf = ensure_dbsnp_available(build, ref, vcf_style)

    indexed_vcf = _ensure_vcf_indexed(vcf_path)

    print(f"Running bcftools annotate...")
    run_cmd(
        ["bcftools", "annotate", "-a", str(dbsnp_vcf), "-c", "ID",
         str(indexed_vcf), "-Oz", "-o", str(annotated_vcf)],
        "bcftools annotate -c ID",
    )
    run_cmd(
        ["bcftools", "index", "-t", str(annotated_vcf)],
        "bcftools index",
    )
    print(f"  Annotated VCF saved: {annotated_vcf}")
    return str(annotated_vcf)


# ---------------------------------------------------------------------------
# SNP panel filtering
# ---------------------------------------------------------------------------


def load_snp_panel(panel_path: str) -> set[str]:
    """Load a SNP panel file (one rsID per line) into a set."""
    panel = set()
    with open(panel_path, "r", encoding="utf-8") as f:
        for line in f:
            rsid = line.strip()
            if rsid and not rsid.startswith("#"):
                panel.add(rsid)
    return panel


def _extract_rsids_from_illumina_csv(csv_path: Path) -> list[str]:
    """
    Parse an Illumina manifest CSV and extract rsIDs from the Name column.

    Illumina manifests have sections [Header], [Assay], [Controls].
    The probe data is in [Assay]; the Name column contains rsIDs for most probes.
    """
    rsids = []
    in_assay = False
    name_idx = None

    with open(csv_path, "r", encoding="utf-8", errors="replace") as f:
        for line in f:
            stripped = line.strip()

            if stripped == "[Assay]":
                in_assay = True
                continue

            if stripped.startswith("[") and stripped.endswith("]") and in_assay:
                break

            if not in_assay:
                continue

            fields = stripped.split(",")

            if name_idx is None:
                try:
                    name_idx = fields.index("Name")
                except ValueError:
                    for i, col in enumerate(fields):
                        if col.strip().lower() == "name":
                            name_idx = i
                            break
                    if name_idx is None:
                        print("  Warning: could not find 'Name' column in manifest")
                        return rsids
                continue

            if len(fields) > name_idx:
                name = fields[name_idx].strip()
                if name.startswith("rs"):
                    rsids.append(name)

    return rsids


def ensure_chip_panel_available(format_version: str, ref_dir: str) -> Path:
    """
    Ensure a 23andMe chip SNP panel file is available in ref_dir.

    Downloads the Illumina manifest for the chip matching format_version,
    extracts rsIDs, and caches the result as a simple text file.
    Returns the path to the panel file.
    """
    ref = Path(ref_dir)
    ref.mkdir(parents=True, exist_ok=True)

    info = ILLUMINA_PANEL_URLS[format_version]
    panel_file = ref / info["panel_file"]

    if panel_file.exists():
        print(f"  Chip panel already available: {panel_file.name}")
        return panel_file

    print(f"  Downloading {info['chip_name']} manifest to extract SNP panel...")
    download_dest = ref / info["download_name"]
    download_file(info["url"], download_dest)

    if info["is_zip"]:
        print(f"  Extracting CSV from ZIP archive...")
        with zipfile.ZipFile(download_dest, "r") as zf:
            csv_names = [n for n in zf.namelist() if n.lower().endswith(".csv")]
            if not csv_names:
                print(f"  Error: no CSV file found inside {download_dest.name}")
                sys.exit(1)
            csv_name = csv_names[0]
            zf.extract(csv_name, ref)
            csv_path = ref / csv_name
    else:
        csv_path = download_dest

    print(f"  Parsing manifest to extract rsIDs...")
    rsids = _extract_rsids_from_illumina_csv(csv_path)
    print(f"  Found {len(rsids):,} rsIDs in manifest")

    with open(panel_file, "w", encoding="utf-8") as f:
        f.write(f"# 23andMe {format_version} chip panel - {info['chip_name']}\n")
        f.write(f"# Extracted from Illumina manifest ({len(rsids)} rsIDs)\n")
        for rsid in sorted(set(rsids)):
            f.write(f"{rsid}\n")

    panel_count = len(set(rsids))
    print(f"  Panel saved: {panel_file.name} ({panel_count:,} unique rsIDs)")

    if csv_path != download_dest and csv_path.exists():
        csv_path.unlink()
    if download_dest.exists():
        download_dest.unlink()

    return panel_file


# ---------------------------------------------------------------------------
# Genotype conversion
# ---------------------------------------------------------------------------


def vcf_genotype_to_23andme(gt_str: str, ref: str, alt: str, chrom: str, is_male: bool = False) -> str:
    """
    Convert a VCF genotype to 23andMe format.

    Autosomes and female X: two letters (e.g. AA, AG).
    Male X, Y, MT: single letter (e.g. A, G).
    Indels: II/DD/DI.
    No-call: --.
    """
    if gt_str in ("./.", ".|.", "."):
        return "--"

    sep = "|" if "|" in gt_str else "/"
    allele_indices = gt_str.split(sep)

    if len(allele_indices) < 2:
        return "--"

    all_alleles = [ref] + (alt.split(",") if alt and alt != "." else [])

    bases = []
    for idx_str in allele_indices:
        if idx_str == ".":
            return "--"
        try:
            idx = int(idx_str)
        except ValueError:
            return "--"
        if idx >= len(all_alleles):
            return "--"
        bases.append(all_alleles[idx])

    is_haploid = chrom in ("Y", "MT") or (chrom == "X" and is_male)

    is_indel = any(len(b) > 1 for b in bases) or any(len(b) > 1 for b in all_alleles if b != ".")

    if is_indel:
        if bases[0] == bases[1]:
            if bases[0] == ref:
                return "D" if is_haploid else "DD"
            return "I" if is_haploid else "II"
        return "DI"

    if is_haploid:
        return bases[0]

    return bases[0] + bases[1]


def generate_header(build: str, version: str) -> str:
    """Generate the 23andMe file header (V3 or V5)."""
    build_labels = {
        "GRCh37": "build 37 (also known as Annotation Release 104)",
        "GRCh38": "build 38 (also known as Annotation Release 106)",
    }
    build_label = build_labels.get(build, f"build {build}")
    date_str = datetime.now().strftime("%a %b %d %H:%M:%S %Y")

    template = HEADER_23ANDME_V5 if version == "V5" else HEADER_23ANDME_V3
    return template.format(date=date_str, build_label=build_label)


# ---------------------------------------------------------------------------
# Main conversion
# ---------------------------------------------------------------------------


def convert_vcf_to_23andme(config: dict) -> None:
    """Main VCF -> 23andMe conversion pipeline."""
    vcf_file = config["input"]["vcf_file"]
    output_file = config["output"]["output_file"]
    format_version = config.get("output", {}).get("format_version", "V5")
    config_build = config.get("reference_build", "GRCh37")
    sample_name = config.get("input", {}).get("sample", None)
    skip_no_rsid = config.get("output", {}).get("skip_no_rsid", False)
    panel_path = config.get("output", {}).get("snp_panel", None)
    filter_by_chip_panel = config.get("output", {}).get("filter_by_chip_panel", False)

    annotation_cfg = config.get("annotation", {})
    annotation_enabled = annotation_cfg.get("enabled", True)
    ref_dir = annotation_cfg.get("ref_dir", None)

    if not Path(vcf_file).exists():
        print(f"Error: VCF file not found: {vcf_file}")
        sys.exit(1)

    if format_version not in ("V3", "V5"):
        print(f"Error: format_version must be 'V3' or 'V5', got: '{format_version}'")
        sys.exit(1)

    # --- Step 1: Detect genome build ---
    print(f"Detecting genome build from VCF...")
    detected_build = detect_genome_build(vcf_file)
    if detected_build:
        build = detected_build
        print(f"  Detected build: {build}")
    else:
        build = config_build
        print(f"  Could not detect build automatically.")
        print(f"  Using YAML fallback: {build}")

    # --- Step 2: Annotate with dbSNP if needed ---
    active_vcf = vcf_file
    if annotation_enabled:
        if ref_dir is None:
            print(f"Error: annotation.enabled is true but annotation.ref_dir is not set.")
            print(f"  Please set annotation.ref_dir in the YAML config.")
            sys.exit(1)
        active_vcf = annotate_vcf_with_dbsnp(vcf_file, build, ref_dir)

    # --- Step 3: Load SNP panel ---
    panel: set[str] | None = None
    if panel_path:
        if not Path(panel_path).exists():
            print(f"Error: SNP panel file not found: {panel_path}")
            sys.exit(1)
        panel = load_snp_panel(panel_path)
        print(f"Loaded SNP panel: {len(panel):,} rsIDs from {panel_path}")
    elif filter_by_chip_panel:
        if ref_dir is None:
            print(f"Error: filter_by_chip_panel is true but annotation.ref_dir is not set.")
            print(f"  Please set annotation.ref_dir in the YAML config.")
            sys.exit(1)
        chip_panel_path = ensure_chip_panel_available(format_version, ref_dir)
        panel = load_snp_panel(str(chip_panel_path))
        print(f"Loaded chip panel ({format_version}): {len(panel):,} rsIDs")

    # --- Step 4: Read VCF and convert ---
    print(f"Reading VCF: {active_vcf}")
    print(f"Output format: 23andMe {format_version}")
    print(f"Build: {build}")

    sample_idx = None
    sample_id = None
    variants = []
    line_count = 0
    panel_hits = 0

    with open_file(active_vcf) as f:
        for line in f:
            if line.startswith("##"):
                continue

            if line.startswith("#CHROM"):
                fields = line.strip().split("\t")
                samples = fields[9:]

                if not samples:
                    print("Error: no samples found in VCF.")
                    sys.exit(1)

                if sample_name:
                    if sample_name in samples:
                        sample_idx = samples.index(sample_name)
                        sample_id = sample_name
                    else:
                        print(f"Error: sample '{sample_name}' not found in VCF.")
                        print(f"  Available samples: {', '.join(samples)}")
                        sys.exit(1)
                else:
                    sample_idx = 0
                    sample_id = samples[0]

                if len(samples) > 1:
                    print(f"  VCF contains {len(samples)} samples. Using: {sample_id}")
                else:
                    print(f"  Sample: {sample_id}")
                continue

            if sample_idx is None:
                continue

            fields = line.strip().split("\t")
            if len(fields) < 10:
                continue

            line_count += 1
            if line_count % 500000 == 0:
                print(f"  Reading VCF: {line_count:,} lines scanned...", end="\r")

            chrom_raw, pos, rsid, ref, alt = fields[0], fields[1], fields[2], fields[3], fields[4]
            chrom = normalize_chrom(chrom_raw)

            if rsid == ".":
                if skip_no_rsid:
                    continue
                rsid = f"i{chrom}_{pos}"

            if panel is not None:
                if rsid in panel:
                    panel_hits += 1
                else:
                    continue

            fmt_fields = fields[8].split(":")
            try:
                gt_index = fmt_fields.index("GT")
            except ValueError:
                continue

            sample_data = fields[9 + sample_idx].split(":")
            if gt_index >= len(sample_data):
                continue

            gt = sample_data[gt_index]
            genotype = vcf_genotype_to_23andme(gt, ref, alt, chrom)

            variants.append((rsid, chrom, pos, genotype))

    # --- Step 5: Report statistics ---
    rsid_count = sum(1 for v in variants if v[0].startswith("rs"))
    internal_count = len(variants) - rsid_count
    print(f"\n  VCF lines scanned: {line_count:,}")
    print(f"  Variants written to output: {len(variants):,}")
    if rsid_count:
        print(f"    With rsID (from dbSNP): {rsid_count:,}")
    if internal_count:
        print(f"    With positional ID (no rsID available): {internal_count:,}")
    if panel is not None:
        print(f"  Chip panel filtering: {panel_hits:,} of {len(panel):,} panel SNPs found in VCF ({100*panel_hits/len(panel):.1f}%)")

    # --- Step 6: Write output ---
    out_path = Path(output_file)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    header = generate_header(build, format_version)

    with open(out_path, "w", encoding="utf-8") as out:
        out.write(header)
        for rsid, chrom, pos, genotype in variants:
            out.write(f"{rsid}\t{chrom}\t{pos}\t{genotype}\n")

    print(f"Output file written: {output_file}")
    print(f"Conversion complete.")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="VCF to 23andMe Converter - Convert VCF files to 23andMe raw data format"
    )
    parser.add_argument(
        "--config",
        type=str,
        required=True,
        help="Path to YAML configuration file",
    )
    args = parser.parse_args()

    config_path = Path(args.config)
    if not config_path.exists():
        print(f"Error: config file not found: {config_path}")
        sys.exit(1)

    config = load_config(config_path)
    convert_vcf_to_23andme(config)


if __name__ == "__main__":
    main()
