from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple


def _position(value: object) -> Optional[int]:
    try:
        return int(str(value))
    except (TypeError, ValueError):
        return None


def load_marker_rows(path: Path) -> Tuple[List[dict], List[str]]:
    with open(path, "r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f, delimiter="\t")
        if not reader.fieldnames:
            raise ValueError(f"Marker TSV has no header: {path}")
        required = {"rsid", "chrom", "position"}
        missing = required.difference(reader.fieldnames)
        if missing:
            raise ValueError(f"Marker TSV is missing required columns {sorted(missing)}: {path}")
        return list(reader), list(reader.fieldnames)


def prune_marker_rows(rows: Sequence[dict], window_bp: int, max_markers: Optional[int] = None) -> Tuple[List[dict], List[dict]]:
    if window_bp < 0:
        raise ValueError("window_bp must be >= 0")
    if max_markers is not None and max_markers <= 0:
        raise ValueError("max_markers must be > 0 when provided")

    kept: List[dict] = []
    removed: List[dict] = []
    kept_positions: Dict[str, List[Tuple[int, str]]] = {}
    for row in rows:
        chrom = str(row.get("chrom", ""))
        pos = _position(row.get("position"))
        rsid = str(row.get("rsid", ""))
        if pos is None:
            kept.append(dict(row))
            continue

        blocked_by = None
        for kept_pos, kept_rsid in kept_positions.get(chrom, []):
            if abs(pos - kept_pos) <= window_bp:
                blocked_by = kept_rsid
                break

        if blocked_by is not None:
            removed_row = dict(row)
            removed_row["pruned_by"] = blocked_by
            removed.append(removed_row)
            continue

        kept.append(dict(row))
        kept_positions.setdefault(chrom, []).append((pos, rsid))
        if max_markers is not None and len(kept) >= max_markers:
            break

    for rank, row in enumerate(kept, start=1):
        row["rank"] = str(rank)
    return kept, removed


def write_marker_rows(rows: Sequence[dict], fieldnames: Sequence[str], output: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    with open(output, "w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, delimiter="\t", extrasaction="ignore")
        writer.writeheader()
        for row in rows:
            writer.writerow(row)


def write_summary(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2)


def run_prune(args: argparse.Namespace) -> int:
    rows, fieldnames = load_marker_rows(args.markers)
    kept, removed = prune_marker_rows(rows, args.window_bp, args.max_markers)
    write_marker_rows(kept, fieldnames, args.output)
    summary_path = args.summary or args.output.with_suffix(args.output.suffix + ".summary.json")
    summary = {
        "markers": str(args.markers),
        "output": str(args.output),
        "window_bp": int(args.window_bp),
        "input_markers": len(rows),
        "kept_markers": len(kept),
        "removed_markers": len(removed),
        "max_markers": args.max_markers,
    }
    write_summary(summary_path, summary)
    print(f"Input markers: {len(rows)}")
    print(f"Kept markers: {len(kept)}")
    print(f"Removed markers: {len(removed)}")
    print(f"Output: {args.output}")
    print(f"Summary: {summary_path}")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Positionally prune ranked SNP ancestry AIMs")
    parser.add_argument("--markers", type=Path, required=True, help="AIM TSV generated by `genomics snp-ancestry markers`")
    parser.add_argument("--output", type=Path, required=True, help="Pruned AIM TSV output path")
    parser.add_argument("--window-bp", type=int, default=50000, help="Remove lower-ranked markers within this distance of a kept marker")
    parser.add_argument("--max-markers", type=int, default=None, help="Stop after retaining at most this many markers")
    parser.add_argument("--summary", type=Path, default=None, help="Optional JSON summary path")
    parser.set_defaults(func=run_prune)
    return parser


def main(argv: Optional[List[str]] = None) -> int:
    args = build_parser().parse_args(argv)
    return int(args.func(args) or 0)


if __name__ == "__main__":
    raise SystemExit(main())
